# Generated by Django 5.2.4 on 2025-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('cores', models.IntegerField(default=0)),
                ('threads', models.IntegerField(default=0)),
                ('ram_gb', models.IntegerField(default=0)),
                ('used_ram_gb', models.IntegerField(default=0)),
                ('available_ram_gb', models.IntegerField(default=0)),
                ('storage_total_gb', models.IntegerField(default=0)),
                ('storage_free_gb', models.IntegerField(default=0)),
                ('storage_used_gb', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
